

services:
  backend:
    build:
      context: ./backend/api
    ports:
      - '5001:5001'
    volumes:
      - ./backend/api:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: sh -c "npx prisma generate && npm run start:dev"
    #command: npm run start:dev
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - backend

  db:
    image: postgres:15.13
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patients

volumes:
  postgres-data:
