services:
  backend:
    build:
      context: ./backend/api
      dockerfile: Dockerfile
    ports:
      - '5001:5001'
    volumes:
      - ./backend/api:/app
      - /app/node_modules
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/aisel"
      command: sh -c "npx prisma db push --accept-data-loss && npm run start:dev"
      # - NODE_ENV=development
    # command: >
    #   sh -c "
    #     npx prisma generate --schema=src/prisma/schema.prisma &&
    #     npx prisma migrate deploy --schema=src/prisma/schema.prisma &&
    #     npx ts-node src/prisma/seed.ts &&
    #     npm run start:dev
    #   "
    #command: sh -c "npx prisma generate --schema=src/prisma/schema.prisma && npx prisma migrate dev --name init --schema=src/prisma/schema.prisma && npx ts-node src/prisma/seed.ts && npm run start:dev"
    #command: sh -c "npx prisma generate && npm run start:dev"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      # DATABASE_URL: "postgresql://postgres:postgres@db:5432/aisel"
      NODE_ENV: development
    command: npm run dev
    depends_on:
      - backend

  db:
    image: postgres:15.13
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aisel
      #POSTGRES_DB: patients

volumes:
  postgres-data:
